govuk-one-login/authentication-infrastructure

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/pre-commit.yml
- .github/workflows/pre-merge-checks-shellscript.yaml
- .gitignore
- .pre-commit-config.yaml
- README.md
- provision-build.sh
- provisioner.sh
Fixup the shell scripts, and add pre-commit checks to ensure that standards are maintained
Also, use pre-established well-known AWS_PROFILE values, to ensure that our AWS config files are consistent between machines.
- Code review
- Run the scripts and ensure they still do what they're supposed to.
> BAU: Shell Script standards

- configuration/di-authentication-build/acceptance-tests-image-repository/parameters.json
- provision-build.sh
Acceptance tests ECR image configuration
Run [AUT-3504] `./provision-build.sh`
[AUT-3504]: https://govukverify.atlassian.net/browse/AUT-3504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3504 - Acceptance tests ECR image configuration

- README.md
- configuration/di-authentication-build/frontend-pipeline/parameters.json
- scripts/read_cloudformation_stack_outputs.sh
Additional code signing configuration for build environment
Deployed by running `./provision-build.sh` script
> AUT-3494 - Additional code signing configuration for build environment 

- configuration/di-authentication-build/frontend-pipeline/parameters.json
- provision-build.sh
- provision-staging.sh
Acceptance test image git repository configuration
Issue: [PSREDEV-1292] [AUT-3504]
Update pipeline with `./provision-build.sh`
[PSREDEV-1292]: https://govukverify.atlassian.net/browse/PSREDEV-1292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AUT-3504]: https://govukverify.atlassian.net/browse/AUT-3504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PSREDEV-1292 - Acceptance test image git repository configuration

- configuration/di-auth-staging/staging-sp-orch-stub-pipeline/parameters.json
- configuration/di-auth-staging/tags.json
- configuration/gds-di-development/build-sp-orch-stub-pipeline/parameters.json
- configuration/gds-di-development/tags.json
- provision-oldbuild.sh
- provision-oldstaging.sh
Orch-stub deployment configurations for secure pipeline deployment.
Deploys to old build and staging accounts.
Promotion enabled: build -> staging
> AUT-3539 - Orch-stub deployment configurations

- .github/CODEOWNERS
Adding codeowners to this repo
> Adding codeowners to this repo

- configuration/di-authentication-staging/frontend-pipeline/parameters.json
- provision-staging.sh
Test stage configured for staging environment
Issue: [AUT-3542]
[AUT-3542]: https://govukverify.atlassian.net/browse/AUT-3542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3542 - Test stage configured for staging environment

- configuration/di-auth-development/authdev1-sp-orch-stub-pipeline/parameters.json
- configuration/di-auth-development/authdev2-sp-orch-stub-pipeline/parameters.json
- configuration/di-auth-development/dev-orch-stub-pipeline/parameters.json
- configuration/di-auth-development/tags.json
- configuration/di-authentication-development/authdev2-acceptance-test-image-repository/parameters.json
- configuration/di-authentication-development/authdev2-basic-auth-sidecar-image-repository/parameters.json
- configuration/di-authentication-development/authdev2-cloudfront-certificate/parameters.json
- configuration/di-authentication-development/authdev2-cloudfront-monitoring/parameters.json
- configuration/di-authentication-development/authdev2-cloudfront-waf/parameters.json
- configuration/di-authentication-development/authdev2-cloudfront/parameters.json
- configuration/di-authentication-development/authdev2-frontend-image-repository/parameters.json
- configuration/di-authentication-development/authdev2-frontend-pipeline/parameters.json
- configuration/di-authentication-development/authdev2-service-down-page-image-repository/parameters.json
- provision-dev.sh
- provision-old-dev.sh
Authdev2 frontend pipeline and cloudfront components bootstrap
Pipeline provisioned for authdev1, authdev2 and dev orchstub deployment
Deploy to target environment
> AUT-3745: Orch stub provisioning in old dev environment

- configuration/di-authentication-development/authdev1-frontend-pipeline/parameters.json
- configuration/di-authentication-development/authdev1-vpc/parameters.json
- configuration/di-authentication-development/authdev2-frontend-pipeline/parameters.json
- configuration/di-authentication-development/authdev2-vpc/parameters.json
- provision-dev.sh
Authdev1 and authdev2 vpcs setup configurations
Issue: [AUT-3768]
Deployed and tested in authdev1 and authdev2. 
[AUT-3768]: https://govukverify.atlassian.net/browse/AUT-3768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3768 - Authdev1 and authdev2 vpcs setup configurations

- configuration/di-authentication-integration/frontend-pipeline/parameters.json
Enable ECS canary in integration env frontend
Issue: [AUT-3544]
[AUT-3544]: https://govukverify.atlassian.net/browse/AUT-3544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3544 - Enable ECS canary in integration env frontend

- configuration/di-authentication-build/dns-zones-and-records/parameters.json
- configuration/di-authentication-development/dns-zones-and-records/parameters.json
- configuration/di-authentication-integration/dns-zones-and-records/parameters.json
- configuration/di-authentication-production/dns-zones-and-records/parameters.json
- configuration/di-authentication-staging/dns-zones-and-records/parameters.json
- configuration/di-authentication-staging/hosted-zones-and-records/parameters.json
- provision-staging.sh
1. Deploy staging environment signin domain resources
2. Domain hosted zone and certificates deployed in two stages
Issue: [AUT-3690]
See linked frontend PR
[AUT-3690]: https://govukverify.atlassian.net/browse/AUT-3690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3690 - Domain hosted zone and certificates deployed in two stages

- provision-dev.sh
deleting new DEV VPC not in use as we are paying standing charges for VPC endpoint , firewall & Nat gateway
We can re provision the new Dev VPC again once we start building dev environment 
see some saving now after deleting unused VPC 
Code Review
> BAU: deleting new DEV VPC

- certificate/template.yaml
- cloudfront-distribution/template.yaml
- configuration/di-authentication-staging/auth-fe-cloudfront-live-certificate/parameters.json
- configuration/di-authentication-staging/auth-fe-cloudfront-wildcard-certificate/parameters.json
- configuration/di-authentication-staging/auth-fe-cloudfront/live-parameters.json
- configuration/di-authentication-staging/auth-fe-cloudfront/wildcard-parameters.json
- configuration/di-authentication-staging/hosted-zones-and-records/zone-only-parameters.json
- provision-cloudfront.sh
- provision-staging.sh
Staging environment CloudFront distribution and hosted zone migration stages
Issue: [AUT-3690]
What changes are in:
1. Transitional templates `cloudfront-distribution/template.yaml` and `certificates/template.yaml` forked from DevPlatform, to support creation of wildcard cert and CF distribution
2. CloudFront, certificates and hosted zones updates at each stage of migration would use its dedicated parameters.json file, to allow all IaC changes reviewed and signed off before go/no-go
3. `provision-<*>.sh` scripts are refactored to support granular updates required at each migration step
Follow along the migration steps in https://govukverify.atlassian.net/wiki/spaces/LO/pages/4773052525/Auth+New+Frontend+Go-live+Release+Plan+-+Draft
and …
> AUT-3690: Staging environment CloudFront distribution and hosted zone migration stages

- configuration/di-authentication-integration/backup-monitoring/parameters.json
- configuration/di-authentication-production/backup-monitoring/parameters.json
- configuration/di-authentication-staging/backup-monitoring/parameters.json
- provision-integration.sh
- provision-production.sh
- provision-staging.sh
AUT-4023: deploy  backup monitoring base stack in staging, int and prod
1. Code Review
> AUT-4023: deploy  backup monitoring base stack in staging, int and prod

- configuration/di-authentication-development/authdev1-ipv-stub-pipeline/parameters.json
- configuration/di-authentication-development/authdev2-ipv-stub-pipeline/parameters.json
- provision-dev.sh
Create secure pipeline for Authdevs IPV stub deployment in Dev Aws Account 
1. Code Review
> AUT-3982: created secure pipeline for Authdevs IPV stub deployment

- configuration/di-authentication-development/authdev1-frontend-pipeline/parameters.json
Disable ECS Blue/green frontend deployment in authdev1
Deploy it `./provision-dev.sh -p`
> Disable ECS Blue/green frontend deployment in authdev1

- configuration/di-authentication-build/vpc/parameters.json
- configuration/di-authentication-integration/vpc/parameters.json
- configuration/di-authentication-production/vpc/parameters.json
- configuration/di-authentication-staging/vpc/parameters.json
Add firewall suricata policies for Egress
Deploy using provision scripts i.e. `./provision-staging.sh -b`
> AUT-4056: Add firewall suricata policies for Egress

- provision-cloudfront.sh
Separate rate limits configurable for ip and aps sessions
Issue: [AUT-4074]
Setup secrets same as old equivalent account
Deploy to target env / sub-env i.e. 
`./provision-cloudfront.sh -e development -s authdev1 -w `
Copy and paste waf rules in text files and compare against old account rule implementation.  
[AUT-4074]: https://govukverify.atlassian.net/browse/AUT-4074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-4074: Separate rate limits configurable for ip and aps sessions

- .editorconfig
- .git-blame-ignore-revs
- .gitignore
- .pre-commit-config.yaml
- migrate-record-set.sh
- provision-build.sh
- provision-cloudfront.sh
- provision-dev.sh
- provision-integration.sh
- provision-old-dev.sh
- provision-production.sh
- provision-staging.sh
- provisioner.sh
- scripts/read_cloudformation_stack_outputs.sh
- scripts/read_parameters.sh
- scripts/read_secrets.sh
- sync-dependencies.sh
- add `.aws-sam` to .gitignore
- Fix the `shfmt` pre-commit hook, so it operates correctly (actually applies formatting changes)
- Apply the correct formatting to the scripts
- Add `.editorconfig`, so IDE formatters will apply the correct formatting
- Update our pre-commit hooks
- _the actual point of this PR_: export the region, rather than updating the global aws profile.
Details for these are in the individual commit messages.
> BAU: fix region configuration in shell scripts

- configuration/di-authentication-build/basic-auth-sidecar-image-repository/parameters.json
- configuration/di-authentication-development/authdev1-basic-auth-sidecar-image-repository/parameters.json
- configuration/di-authentication-development/authdev2-basic-auth-sidecar-image-repository/parameters.json
- configuration/di-authentication-development/basic-auth-sidecar-image-repository/parameters.json
- provision-build.sh
- provision-dev.sh
Remove provisioning for basic auth sidecar repo
Code review
> AUT-3846: Remove basic auth sidecar ECR repo

- configuration/di-authentication-development/auth-fe-cloudfront-live-certificate/parameters.json
- configuration/di-authentication-development/auth-fe-cloudfront-monitoring/parameters.json
- configuration/di-authentication-development/auth-fe-cloudfront-waf/parameters.json
- configuration/di-authentication-development/auth-fe-cloudfront/live-parameters.json
- provision-dev.sh
- scripts/read_parameters.sh
- scripts/read_secrets.sh
Dev environment CloudFront resources configurations
Issue: [AUT-3942]
See jira ticket for outputs of `./provision-dev.sh` and `./provision-cloudfront.sh -e development` scripts. 
[AUT-3942]: https://govukverify.atlassian.net/browse/AUT-3942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3942: Dev environment CloudFront resources configurations

- .github/workflows/pre-commit.yml
- .github/workflows/pre-merge-checks-shellscript.yaml
- .github/workflows/require-pinned-github-actions.yml
> BAU: require pinned github actions

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- configuration/di-authentication-development/auth-fe-cloudfront/tags.json
- configuration/di-authentication-development/authdev1-cloudfront/tags.json
- configuration/di-authentication-development/authdev2-cloudfront/tags.json
- migrate-record-set.sh
- provision-build.sh
- provision-cloudfront.sh
- provision-dev.sh
- provision-integration.sh
- provision-old-dev.sh
- provision-production.sh
- provision-staging.sh
- provisioner.sh
Migrate Auth CloudFront to use FMS WAF in dev account
Also, fix a couple of small annoyances.
- code review
- deploy to dev accounts, ensure that nothing weird changes (I've already applied this, so there shouldn't be any at all!)
> BAU: FMS Migration

- configuration/di-authentication-build/auth-fe-cloudfront/tags.json
- provisioner.sh
- **BAU: Add FMSGlobalCustomPolicy tag to build CF**
- **BAU: change casing of `Y/n` prompt to `y/n`**
details in commit messages
Code review
> BAU: Migrate `build` cloudfront WAF to FMS

- configuration/di-authentication-staging/auth-fe-cloudfront/tags.json
> BAU: Associate FMS waf with staging frontend cloudfront

- configuration/di-authentication-production/auth-fe-cloudfront/tags.json
BAU: Add additional tag on CF for FMS WAF migration
1. Code Review
> BAU: Add additional tag on CF for FMS WAF migration

- configuration/di-authentication-build/auth-fe-cloudfront-waf/parameters.json
- configuration/di-authentication-development/auth-fe-cloudfront-waf/parameters.json
- configuration/di-authentication-development/authdev1-cloudfront-waf/parameters.json
- configuration/di-authentication-development/authdev2-cloudfront-waf/parameters.json
- configuration/di-authentication-integration/auth-fe-cloudfront-waf/parameters.json
- configuration/di-authentication-production/auth-fe-cloudfront-waf/parameters.json
- provision-cloudfront.sh
[AUT-4261 ] : Remove WAF provisioning function , We have migrated to use FMS managed WAF so deleting unused Auth WAF 
1. Code Review
> AUT-4261: Remove WAF provisioning function

- configuration/di-authentication-build/frontend-apitest-image-repository/parameters.json
- configuration/di-authentication-development/frontend-apitest-image-repository/parameters.json
- provision-build.sh
- provision-dev.sh
Separate ECR repo for apitest variant of frontend
> AUT-4503: Separate ECR repo for apitest variant of frontend

- provision-build.sh
- provision-dev.sh
- provision-integration.sh
- provision-staging.sh
AUT-4638:Updated lambda code storage Stack version to  v0.0.7
1. Code Review
> AUT-4638:Updated lambda code storage Stack version to  v0.0.7

- configuration/di-authentication-build/authentication-api-pipeline/parameters.json
- configuration/di-authentication-development/authdev1-api-pipeline/parameters.json
- configuration/di-authentication-development/authdev2-api-pipeline/parameters.json
- configuration/di-authentication-development/authentication-api-pipeline/parameters.json
- configuration/di-authentication-integration/authentication-api-pipeline/parameters.json
- configuration/di-authentication-production/authentication-api-pipeline/parameters.json
- configuration/di-authentication-staging/authentication-api-pipeline/parameters.json
Adding Orch dynamo Account ID
1. Code Review
> Adding Orch dynamo Account ID

- configuration/di-authentication-build/build-stubs-api-pipeline/parameters.json
- configuration/di-authentication-development/authdev1-stubs-api-pipeline/parameters.json
- configuration/di-authentication-development/authdev2-stubs-api-pipeline/parameters.json
- configuration/di-authentication-development/authdev3-api-pipeline/parameters.json
- configuration/di-authentication-development/authdev3-stubs-api-pipeline/parameters.json
- configuration/di-authentication-development/dev-smoke-test-pipeline/parameters.json
- configuration/di-authentication-development/dev-stubs-api-pipeline/parameters.json
- provision-build.sh
- provision-dev.sh
Aut 3815 setup stubs secure deployment pipeline
1. Code Review
> Aut 3815 setup stubs secure deployment pipeline
