govuk-one-login/authentication-infrastructure

- .gitignore
- README.md
- configuration/di-authentication-build/auth-fe-cloudfront-certificate/parameters.json
- configuration/di-authentication-build/auth-fe-cloudfront-monitoring/parameters.json
- configuration/di-authentication-build/auth-fe-cloudfront-waf/parameters.json
- configuration/di-authentication-build/auth-fe-cloudfront/parameters.json
- configuration/di-authentication-build/dns-zones-and-records/parameters.json
- provision-build.sh
- provision-cloudfront-build.sh
- provisioner.sh
- scripts/read_parameters.sh
- scripts/read_secrets.sh
- sync-dependencies.sh
Run `./provision-cloudfront-<environment>.sh` to deploy CloudFront distribution and additional dependencies described in the [CloudFront header](https://govukverify.atlassian.net/wiki/spaces/DID/pages/4026401532/Part+1+-+Deploying+CloudFront) trust initiative.
sync-dependencies.sh - deploys and maintains a shallow copy of authentication-frontend repository, in order to source several cloudformation templates used in the provision scripts
read_secrets.sh - extracts all secrets stored in AWS Secrets Manager named as `/deploy/\${Environment}/secret-name` and export to shell as `secret-name=value`
read_parameters.sh- extracts all parameters stored in AWS Systems Manager Parameter store named as `/deploy/\${Environment}/param-name` and export to shell as `param-name=value`
Both secrets and …
> AUT-3365 - Deploy Cloudfront distribution for build account

- configuration/di-authentication-development/authdev1-frontend-pipeline/parameters.json
- configuration/di-authentication-staging/frontend-pipeline/parameters.json
- provision-staging.sh
Enable ECS Canary in authdev1 and staging envs
Issue: [AUT-3546]
[AUT-3546]: https://govukverify.atlassian.net/browse/AUT-3546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3546 - Enable ECS Canary in authdev1 and staging envs

- configuration/di-authentication-build/build-notifications/parameters.json
- configuration/di-authentication-build/frontend-pipeline/parameters.json
- configuration/di-authentication-development/authdev1-frontend-pipeline/parameters.json
- configuration/di-authentication-development/authdev2-frontend-pipeline/parameters.json
- configuration/di-authentication-development/build-notifications/parameters.json
- configuration/di-authentication-integration/build-notifications/parameters.json
- configuration/di-authentication-integration/frontend-pipeline/parameters.json
- configuration/di-authentication-production/build-notifications/parameters.json
- configuration/di-authentication-production/frontend-pipeline/parameters.json
- configuration/di-authentication-staging/build-notifications/parameters.json
- configuration/di-authentication-staging/frontend-pipeline/parameters.json
- provision-build.sh
- provision-dev.sh
- provision-integration.sh
- provision-production.sh
- provision-staging.sh
- build-notifications stack setup for dev to production environments
- frontend pipelines configured to trigger notifications on failures 
- currently posting notifications to #di-auth-secure-pipeline-notifications channel
Trigger a deployment or test or promotion failure in ci/cd pipeline
See notifications appearing in slack channel
> AUT-3850: frontend pipeline build failure notifications setup

- provision-cloudfront.sh
- scripts/read_parameters.sh
Workaround in scripts/read_parameters.sh to convert hyphens to underscore
Retrieve signin-sp hosted zone id, required for certificate validation
In order to deploy in i.e. build environment, run `./provision-cloudfront.sh build`
> AUT-3860: Support for retrieving signin-sp hosted zone id

- dns-records-signin-integration.json
- dns-records-signin-prod.json
- dns-records-signin-production.json
- migrate-record-set.sh
Adding Script to copy  prod DNS records from existing signin ZONE Id to New signin ZONE Id in new AWS account.
Note: This script only creates a DNS record in new Zone ID however to make this records we need to do Name server Delegation in root domain 
1. Code Review
> AUT-3694 copy zone id record set in prod

- configuration/di-authentication-production/build-notifications/parameters.json
Prod build-notifications stack is the InitialNotificationStack
Updated parameters.json to reflect that
`./provision-production.sh` returns no change
> AUT-3944: Prod build-notifications stack is the InitialNotificationStack

- configuration/di-authentication-integration/auth-fe-cloudfront-live-certificate/parameters.json
- configuration/di-authentication-integration/auth-fe-cloudfront-wildcard-certificate/parameters.json
- configuration/di-authentication-integration/auth-fe-cloudfront/live-parameters.json
- configuration/di-authentication-integration/auth-fe-cloudfront/wildcard-parameters.json
- configuration/di-authentication-integration/hosted-zones-and-records/parameters.json
- configuration/di-authentication-integration/hosted-zones-and-records/zone-only-parameters.json
- provision-integration.sh
Changes:
- Build provision script refactor: divided into functional sections i.e base_stacks, pipelines etc and deployment controlled via args
- Stack input parameters.json files for intermediate and final migration stages
Issue: [AUT-3693]
Run `./provision-build.sh` and `./provision-cloudfront.sh`. Should print usage if no args, specific stacks updated as per args input
[AUT-3693]: https://govukverify.atlassian.net/browse/AUT-3693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3693: Integration provision script refactor, parameters for migration intermediate stages

- configuration/di-authentication-build/auth-fe-cloudfront-live-certificate/parameters.json
- configuration/di-authentication-build/auth-fe-cloudfront-wildcard-certificate/parameters.json
- configuration/di-authentication-build/auth-fe-cloudfront/live-parameters.json
- configuration/di-authentication-build/auth-fe-cloudfront/wildcard-parameters.json
- configuration/di-authentication-build/hosted-zones-and-records/parameters.json
- configuration/di-authentication-build/hosted-zones-and-records/zone-only-parameters.json
- provision-build.sh
- provision-staging.sh
Changes:
- Build provision script refactor: divided into functional sections i.e base_stacks, pipelines etc and deployment controlled via args
- Stack input parameters.json files for intermediate and final migration stages
Issue: [AUT-3689]
Run `./provision-build.sh` and `./provision-cloudfront.sh`. Should print usage if no args, specific stacks updated as per args input
[AUT-3689]: https://govukverify.atlassian.net/browse/AUT-3689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3689: Build provision script refactor, parameters for migration intermediate stages

- configuration/di-authentication-production/auth-fe-cloudfront-live-certificate/parameters.json
- configuration/di-authentication-production/auth-fe-cloudfront-wildcard-certificate/parameters.json
- configuration/di-authentication-production/auth-fe-cloudfront/live-parameters.json
- configuration/di-authentication-production/auth-fe-cloudfront/wildcard-parameters.json
- configuration/di-authentication-production/hosted-zones-and-records/parameters.json
- configuration/di-authentication-production/hosted-zones-and-records/zone-only-parameters.json
- provision-cloudfront.sh
- provision-production.sh
Changes:
- Prod provision script refactor:
- divided into functional sections i.e base_stacks, pipelines etc and deployment controlled via args
- introduced CONFIRM_CHANGESET_OPTION in provision_notification to prompt for user input to apply changeset 
- Stack input parameters.json files for intermediate and final migration stages
Issue: [AUT-3694]
Run ./provision-production.sh and ./provision-cloudfront.sh. Should print usage if no args, specific stacks updated as per args input
Default behaviour: user will be prompted to confirm apply changeset when a diff is found. NOTE: Create stacks do not prompt
[AUT-3694]: https://govukverify.atlassian.net/browse/AUT-3694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3694: Prod provision scripts refactored, parameters for migration intermediate stages

- configuration/di-authentication-staging/frontend-pipeline/parameters.json
Disable ECS canary deployment in staging
Issue: [AUT-3943]
Deploy to staging `./provision-staging.sh -p`
[AUT-3943]: https://govukverify.atlassian.net/browse/AUT-3943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3943 - Disable ECS canary deployment in staging

- configuration/di-authentication-development/authdev1-frontend-pipeline/parameters.json
- configuration/di-authentication-development/authdev2-frontend-pipeline/parameters.json
- provision-dev.sh
1. Authdevs moved to shared vpc
2. provision-dev.sh refactored to match higher envs
Issue: [AUT-3941]
provision-dev.sh supports input params
```
$ ./provision-dev.sh 
Script to bootstrap di-authentication-development account
Usage:
./provision-dev.sh [-b|--base-stacks] [-p|--pipelines] [-t|--transitional-zone-resources]
Options:
-b, --base-stacks                      Provision base stacks
-p, --pipelines                        Provision secure pipelines
-t, --transitional-zone-resources      Provision transitional hosted zone, certificates and SSM params
```
Update pipelines by running `./provision-dev.sh  -p`
[AUT-3941]: https://govukverify.atlassian.net/browse/AUT-3941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3941 - Authdevs moved to shared vpc, provision-dev.sh refactored to match higher envs

- configuration/di-authentication-build/frontend-pipeline/parameters.json
- configuration/di-authentication-integration/frontend-pipeline/parameters.json
- configuration/di-authentication-production/frontend-pipeline/parameters.json
Disable frontend ECS Blue/green deployment
Issue: [AUT-3990]
Env level configuration. Can only be tested on the target env. 
Deploy pipeline changes to the target environment `./provision-<environment>.sh -p`, delete frontend stack and redeploy. 
[AUT-3990]: https://govukverify.atlassian.net/browse/AUT-3990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3990: Disable frontend ECS Blue/green deployment

- configuration/di-authentication-integration/build-notifications/parameters.json
Moving integration frontend pipeline notifications to the `#di-auth-developers` channel, where the Authentication team members monitor any deployment failures.
Step 1.17 of migration https://govukverify.atlassian.net/wiki/spaces/LO/pages/4773052525/Auth+New+Frontend+Go-live+Release+Plan
> AUT-3693: Move integration pipeline alerts to dev channel

- configuration/di-authentication-build/vpc/parameters.json
- configuration/di-authentication-integration/vpc/parameters.json
- configuration/di-authentication-production/vpc/parameters.json
- configuration/di-authentication-staging/vpc/parameters.json
Sync DNS firewall allowlisting with old accounts
Issue: [AUT-4049]
Compare side-by-side with Allow-list domains configuration in old accounts
[AUT-4049]: https://govukverify.atlassian.net/browse/AUT-4049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-4049: Sync DNS firewall allowlisting with old accounts

- configuration/di-authentication-production/auth-fe-cloudfront-notification/parameters.json
- configuration/di-authentication-production/build-notifications/parameters.json
Switch pipeline and cache hit alerts to live channels
Issue: [AUT-3694]
Following step 4.3 in the [release plan](https://govukverify.atlassian.net/wiki/spaces/LO/pages/4773052525/Auth+New+Frontend+Go-live+Release+Plan)
[AUT-3694]: https://govukverify.atlassian.net/browse/AUT-3694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3694: switch pipeline and cache hit alerts to live channels

- provision-cloudfront.sh
- scripts/read_cloudformation_stack_outputs.sh
- scripts/read_parameters.sh
- scripts/read_secrets.sh
Refactor helper scripts to read aws_region from env
Issue: [AUT-3689]
Run `./provision-cloudfront.sh` with a CloudFront distribution change i.e. `./provision-cloudfront.sh -e build -d live`
[AUT-3689]: https://govukverify.atlassian.net/browse/AUT-3689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-3689: refactor helper scripts to read aws_region from env

- configuration/di-authentication-build/frontend-pipeline/parameters.json
- configuration/di-authentication-development/frontend-pipeline/parameters.json
- configuration/di-authentication-integration/frontend-pipeline/parameters.json
- configuration/di-authentication-production/frontend-pipeline/parameters.json
- configuration/di-authentication-staging/frontend-pipeline/parameters.json
ECS Canary deployment enabled across environments
ECSAllAtOnce - dev, staging
ECSCanary10Percent5Minutes - build, integration and production
Verify pipeline setup is recommend as per the [deployment guide](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance#Step-1%3A-Update-your-pipeline-stack)
> AUT-3991: ECS Canary deployment enabled across environments

- configuration/di-authentication-build/vpc/parameters.json
- configuration/di-authentication-development/vpc/parameters.json
- configuration/di-authentication-integration/vpc/parameters.json
- configuration/di-authentication-production/vpc/parameters.json
- configuration/di-authentication-staging/vpc/parameters.json
- provision-build.sh
- provision-dev.sh
- provision-integration.sh
- provision-production.sh
- provision-staging.sh
Upgrade vpc stack with vpc peering configurations
Issue: [AUT-4067]
Slack thread with relevant discussion https://gds.slack.com/archives/C082N2A586R/p1742564802498929
no mechanism to import an existing route table entry in an existing route table managed by cloudformation :clown_face:. Simply trying to add one will return an "AlreadyExists" error.
SRE :zero: -downtime add -> remove - modify
Step 1. Add: via Cloudformation, add a /15 catch-all cidr range
Step 2. Remove: existing /16 entry that was manually added before
Step 3. Change: update /15 to /16
This PR is **step 1 of 3.** 
[AUT-4067]: https://govukverify.atlassian.net/browse/AUT-4067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-4067: Upgrade vpc stack with vpc peering configurations

- provision-staging.sh
Bump vpc stack in staging to v2.9.0
Issue: [AUT-4067]
Meant to be part of https://github.com/govuk-one-login/authentication-infrastructure/pull/62
[AUT-4067]: https://govukverify.atlassian.net/browse/AUT-4067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-4067: Bump vpc stack in staging to v2.9.0

- alerts/template.yaml
- configuration/di-authentication-build/auth-fe-cloudfront-notification/parameters.json
- configuration/di-authentication-build/cloudwatch-alarm-notification/parameters.json
- configuration/di-authentication-development/auth-fe-cloudfront-notification/parameters.json
- configuration/di-authentication-development/cloudwatch-alarm-notification/parameters.json
- configuration/di-authentication-integration/auth-fe-cloudfront-notification/parameters.json
- configuration/di-authentication-integration/cloudwatch-alarm-notification/parameters.json
- configuration/di-authentication-production/auth-fe-cloudfront-notification/parameters.json
- configuration/di-authentication-production/cloudwatch-alarm-notification/parameters.json
- configuration/di-authentication-staging/auth-fe-cloudfront-notification/parameters.json
- configuration/di-authentication-staging/cloudwatch-alarm-notification/parameters.json
- provision-build.sh
- provision-cloudfront.sh
- provision-dev.sh
- provision-integration.sh
- provision-production.sh
- provision-staging.sh
Notification stack to integrate with CloudWatch alarms
Alerts stack has been refactored to take Environment as param, instead of AccountAlias.
Creates a notification stack in the eu-west-2 region. SNS topic referenced in frontend stack via SSM parameter.
Deploy to target environment i.e. `./provision-dev.sh --notification`.
> AUT-4238:  Notification stack to integrate with CloudWatch alarms

- provision-build.sh
- provision-dev.sh
- provision-staging.sh
VPC template version bump that adds private subnets routes thru peering connection
Using a dev vpc template in dev, build and staging till a published version is available
Issue: [AUT-4301]
[AUT-4301]: https://govukverify.atlassian.net/browse/AUT-4301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-4301: adds private subnets routes thru peering connection

- configuration/di-authentication-build/frontend-image-repository/parameters.json
- configuration/di-authentication-build/service-down-page-image-repository/parameters.json
- configuration/di-authentication-development/authdev1-frontend-image-repository/parameters.json
- configuration/di-authentication-development/authdev1-service-down-page-image-repository/parameters.json
- configuration/di-authentication-development/authdev2-frontend-image-repository/parameters.json
- configuration/di-authentication-development/authdev2-service-down-page-image-repository/parameters.json
- configuration/di-authentication-development/frontend-image-repository/parameters.json
- configuration/di-authentication-development/service-down-page-image-repository/parameters.json
- provision-build.sh
- provision-dev.sh
Configure ECR repo lifecycle policy to retain the latest 100 images.
In compliance with RFC0096 - https://github.com/govuk-one-login/architecture/blob/main/rfc/0096-ecr-lifecycle-policy.md
Also bumped the `container-image-repository` stack version to [v3.0.0](https://github.com/govuk-one-login/devplatform-deploy/blob/main/container-image-repository/CHANGELOG.md#v300---2025-03-18)
Issue: [AUT-4350]
Test deployment i.e. `./provision-dev.sh --base-stacks`
Detailed test reports in the JIRA ticket
[AUT-4350]: https://govukverify.atlassian.net/browse/AUT-4350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AUT-4350: Configure ECR repo lifecycle policy to retain the latest 100 images

- provision-integration.sh
Bumping vpc template version from v2.9.0 -> v2.9.2 in integration.
Includes logic to create private Subnet routes through vpc peering connection.
This is required by lambda deployed to private subnets to have cross-account redis access
> AUT-4538: Private Subnet routes through vpc peering connection
